"use client";

import { motion } from "framer-motion";
import React from "react";
import Accordion from "../Accordion";
import { Divider } from "../Divider";

const Faqs = () => {
  return (
    <motion.section
      id="faqs"
      className="relative w-full flex flex-col items-start justify-center gap-12 mt-[128px] pb-20 pt-48 px-12 max-w-[800px]"
    >
      <div className="z-10 flex flex-col gap-2">
        <h2>FAQs</h2>
        <p className="text-textd">
          Answers to the most frequently asked questions.
        </p>
      </div>

      <div className="flex flex-col w-full gap-4">
        <Accordion title="How do you handle my data?" active>
          We prioritize your privacy and security. All data is encrypted and stored securely, 
          ensuring that your information is protected at all times.

        </Accordion>
        <Divider />

        <Accordion title="What's the difference between the Entrepreneur and Business plan?">
          The Entrepreneur plan is designed for individuals and small teams, 
          offering essential features to kickstart your projects. 
          The Business plan provides advanced tools and support for larger teams and enterprises, 
          enabling greater collaboration and productivity.


        </Accordion>
        <Divider />

        <Accordion title="Will an API be available?">
          Yes, we offer an API to integrate our AI capabilities seamlessly into your applications. 
          Detailed documentation and support are provided to help you get started quickly.

        </Accordion>
        <Divider />

        <Accordion title="Can I use these images commercially?">
          Absolutely. You have full commercial rights to use the images generated by our platform, 
          allowing you to leverage them in your projects, marketing materials, and more.
        </Accordion>
        <Divider />

        <Accordion title="How does team payments work?">
          Team payments are streamlined to ensure simplicity and transparency. 
          Each team member can be billed individually, or the team leader can manage 
          a consolidated payment for the entire team. 
          Flexible options are available to suit your team's needs.
        </Accordion>
        <Divider />

        <Accordion title="What are the % on the referral program?">
          Our referral program offers a generous commission structure. 
          You can earn up to 40% of the subscription fee for every new 
          user you refer who signs up for a paid plan. This helps you benefit 
          while sharing the advantages of our platform with others.
        </Accordion>
      </div>
    </motion.section>
  );
};

export default Faqs;
